global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "conforl_rules.yml"

scrape_configs:
  - job_name: 'conforl'
    static_configs:
    - targets: ['conforl-service:80']
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: 'kubernetes-nodes'
    kubernetes_sd_configs:
    - role: node
    relabel_configs:
    - source_labels: [__address__]
      regex: '(.*):10250'
      target_label: __address__
      replacement: '${1}:9100'

  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
    - role: pod
    relabel_configs:
    - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
      action: keep
      regex: true

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093
