global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "conforl_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'conforl-app'
    static_configs:
      - targets: ['conforl-app:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s
    
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
