apiVersion: v1
kind: Service
metadata:
  name: conforl-service
  namespace: conforl
  labels:
    app: conforl
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: conforl
